# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Proiect_3/Block_Design/Block_Design.srcs/sources_1/bd/Block_Design/ip/Block_Design_xbar_1/Block_Design_xbar_1.xci
# IP: The module: 'Block_Design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Proiect_3/Block_Design/Block_Design.gen/sources_1/bd/Block_Design/ip/Block_Design_xbar_1/Block_Design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Design_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Proiect_3/Block_Design/Block_Design.srcs/sources_1/bd/Block_Design/ip/Block_Design_xbar_1/Block_Design_xbar_1.xci
# IP: The module: 'Block_Design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Proiect_3/Block_Design/Block_Design.gen/sources_1/bd/Block_Design/ip/Block_Design_xbar_1/Block_Design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Design_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
